arrowParens: always
bracketSameLine: false
bracketSpacing: true
endOfLine: lf
singleQuote: true
jsxSingleQuote: true
printWidth: 100
requirePragma: false
semi: false
tabWidth: 2
trailingComma: 'none'
useTabs: false
